apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: CHANGE_ME
  namespace: cert-manager
spec:
  secretName: CHANGE_ME
  duration: 2160h # 90d
  renewBefore: 360h # 15d
    # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: "*.CHANGE_ME"
  isCA: false
  # keySize: 2048
  # keyAlgorithm: rsa
  # keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - "*.CHANGE_ME"
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    #    group: cert-manager.io
